name: python3
channels:
    - https://conda.anaconda.org/menpo
    - conda-forge
    - https://conda.anaconda.org/kne
    - https://conda.binstar.org/tlatorre
    - https://conda.anaconda.org/cjs14
    - jjhelmus
    - soumith
dependencies:
    - python==3.5.2
    - numpy
    - matplotlib
    - jupyter
    - opencv3
    - pillow
    - scikit-learn
    - scikit-image
    - scipy
    - h5py
    - eventlet
    - flask-socketio
    - seaborn
    - pandas
    - ffmpeg
    - imageio=2.1.2
    - pyqt=4.11.4
    - joblib=0.10.3
    - mako
    - ipywidgets
    - numba
    - flask
    - pybox2d
    - pygame
    - pytorch==0.1.9
    - torchvision==0.1.6
    - mpi4py
    - path.py
    - python-dateutil
    - pip:
        - moviepy
        - tensorflow==0.12.1
        - git+https://github.com/fchollet/keras.git
        - Pillow
        - atari-py
        - pyprind
        - ipdb
        - boto3
        - PyOpenGL
        - nose2
        - pyzmq
        - tqdm
        - msgpack-python
        - mujoco_py
        - cached_property
        - line_profiler
        - cloudpickle
        - Cython
        - redis
        - git+https://github.com/Theano/Theano.git@adfe319ce6b781083d8dc3200fb4481b00853791#egg=Theano
        - git+https://github.com/neocxi/Lasagne.git@484866cf8b38d878e92d521be445968531646bb8#egg=Lasagne
        - git+https://github.com/plotly/plotly.py.git@2594076e29584ede2d09f2aa40a8a195b3f3fc66#egg=plotly
        - awscli
        - git+https://github.com/openai/gym.git@93d554bdbb4b2d29ff1a685158dbde93b36e3801#egg=gym
        - pyglet
        - git+https://github.com/neocxi/prettytensor.git
        - jupyter
        - progressbar2
        - chainer==1.18.0
        - numpy-stl==2.2.0
        - nibabel==2.1.0
        - pylru==1.0.9
